syntax = "proto3";

package textInserting;

import "constants/responsesCodes.proto";
import "Positions/positions.proto";

option java_multiple_files = true;
option java_package = "org.ide.WebWorker.Text.Inserting";

message InsertTextServerRequest {
    string filePath = 1;
    positions.CursorPosition position = 2;
    string text = 3;
}

message InsertTextServerResponse {
    responsesCodes.InsertTextCode code = 1;
    string error = 2;
}

message InsertTextClientRequest {
    string filePath = 1;
    positions.CursorPosition position = 2;
    string text = 3;
}

message InsertTextClientResponse {
    responsesCodes.CodeChangingCode code = 1;
    string error = 2;
}