syntax = "proto3";

package fileSystemCreate;

import "constants/responsesCodes.proto";
import "fileSystem/file-system-components.proto";

option java_multiple_files = true;
option java_package = "org.WebWorker.FileSystem.Create";


message CreateServerRequest {
    string relativeFilePath = 1;
    fileSystemComponents.FileType file_type = 2;
}

message CreateServerResponse {
    responsesCodes.CreateFileCode code = 1;
    string error = 2;
}

message CreateClientRequest {
    string relativeFilePath = 1;
    fileSystemComponents.FileType file_type = 2;
}

message CreateClientResponse {
    responsesCodes.CreateFileCode code = 1;
    string error = 2;
}

