syntax = "proto3";

package fileSystemMove;

import "constants/responsesCodes.proto";
import "fileSystem/file-system-components.proto";

option java_multiple_files = true;
option java_package = "org.ide.WebWorker.FileSystem.Move";


message MoveServerRequest {
    string relativeFilePath = 1;
    string pathToMove = 2;
    fileSystemComponents.FileType file_type = 3;
}

message MoveServerResponse {
    responsesCodes.MoveCode code = 1;
    string error = 2;
}

message MoveClientRequest {
    string relativeFilePath = 1;
    string pathToMove = 2;
    fileSystemComponents.FileType file_type = 3;
}

message MoveClientResponse {
    responsesCodes.MoveCode code = 1;
    string error = 2;
}
